name = "Dartis-Craft - Karui 2 Packwiz Beta"
author = "Dartis-Craft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dee4db655972c1358e3b5c6e5423869b3c01b1c6791dc881cce94302af157864"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
