name = "Dartis-Craft - Karui 2 Packwiz Beta"
author = "Dartis-Craft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e149a50b62e73081278dd802b98563c7812c276261fb51aaf6807b7f98d40b6d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
