name = "Dartis-Craft - Karui 2 Packwiz Beta"
author = "Dartis-Craft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67877b02944d5d302e556b1213f24bead2c991875731149f3a547651b40bdbe9"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
