name = "Dartis-Craft - Karui 2 Packwiz Beta"
author = "Dartis-Craft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b753008a7283eb8d950747cd51fda69f498f94d66ec431db95e4eeff6c0f8bae"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
